version: '3'
services:
  web:
    container_name: elixir-phoenix
    restart: always
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: db-postgres
    image: "postgres:10"
    restart: always
    ports:
      - "5432:5432"
